services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urlshortener
    ports:
      - 5432:5432
    volumes:
      - postgres_vol:/var/lib/postgresql/data

volumes:
  postgres_vol:
