POST http://localhost:3333/auth/signup
Content-Type: application/json

{
  "email": "jQpa@example.com",
  "password": "Testing@123"
}

###

POST http://localhost:3333/auth/signin
Content-Type: application/json

{
  "email": "jQpa@example.com",
  "password": "Testing@123"
}
