POST http://localhost:3333/auth/signup
Content-Type: application/json

{
  "email": "jQpa@example.com",
  "password": "Testing@123"
}

###

POST http://localhost:3333/auth/signin
Content-Type: application/json

{
  "email": "jQpa@example.com",
  "password": "Testing@123"
}

###

POST http://localhost:3333/links
Content-Type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoialFwYUBleGFtcGxlLmNvbSIsImlhdCI6MTcyNDI1NjE1NiwiZXhwIjoxNzI0MjkyMTU2fQ.8vQH2cFSFnfLzXV_7xLRcfxeBzBB-ZiHxqp9zKKxYMk; Path=/; Expires=Thu, 22 Aug 2024 16:02:36 GMT; HttpOnly; Secure

{
  "url": "https://teddy360.com.br/material/marco-legal-das-garantias-sancionado-entenda-o-que-muda/"
}


###
GET http://localhost:3333/3u6m63


###
GET http://localhost:3333/links
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoialFwYUBleGFtcGxlLmNvbSIsImlhdCI6MTcyNDI1ODA1OCwiZXhwIjoxNzI0Mjk0MDU4fQ.b0y0U9yRAavIPy-7Gx2PdMQ7J_D15y2aHAif4_wtWx4; Path=/; Expires=Thu, 22 Aug 2024 16:34:18 GMT; HttpOnly; Secure
